# Generated by Django 3.0.4 on 2020-05-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('genres', models.TextField()),
                ('tags', models.TextField()),
                ('developers', models.TextField()),
                ('publishers', models.TextField()),
                ('platforms', models.TextField()),
                ('places_to_purchase', models.TextField()),
                ('rec_1', models.TextField()),
                ('rec_2', models.TextField()),
                ('rec_3', models.TextField()),
                ('rec_4', models.TextField()),
                ('rec_5', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'games',
            },
        ),
    ]
